### ISSUE TITLE
Fix Default Title

### ISSUE THREAD

**Issue by maxbeizer** [centresource/preseason#48]
https://github.com/centresource/preseason/blob/01514b644ae24a7f2be06039232dab9292498612/lib/preseason/templates/playbook/app/views/layouts/application.html.erb#L9

Why I made this "foo" I have no idea

**Comment by maxbeizer** [comment]
@rclements any progress on this?

**Comment by rclements** [comment]
@maxbeizer Yeah haven't pushed it yet because I'm working on testing the change locally still.
