### ISSUE TITLE
Fix Marketing Site Code Blocks in FF

### ISSUE THREAD

**Issue by maxbeizer** [centresource/preseason#66]
The code in the `<pre>` looks like the veritcal align is off. h/t @stephenyeargin

**Comment by stephenyeargin** [comment]
![screen shot 2015-02-20 at 4 34 21 pm](https://cloud.githubusercontent.com/assets/80459/6310619/60d436f4-b91e-11e4-96e6-d6f1bdc49794.png)

It looks like there may be a `<code>` tag inside the `<pre>` as well. Probably overkill. when I removed that in the DOM, it formatted it a bit nicer.

![screen shot 2015-02-20 at 4 35 39 pm](https://cloud.githubusercontent.com/assets/80459/6310637/8589d31e-b91e-11e4-9ae1-26eb553199ee.png)
